"""drop uniqueness from several names

Revision ID: 281fc4ff4ad4
Revises: 6f107c3dbb23
Create Date: 2020-09-25 17:42:31.156875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '281fc4ff4ad4'
down_revision = '6f107c3dbb23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_blockchain_contracts_name', table_name='blockchain_contracts')
    op.create_index(op.f('ix_blockchain_contracts_name'), 'blockchain_contracts', ['name'], unique=False)
    op.drop_index('ix_catalog_items_name', table_name='catalog_items')
    op.create_index(op.f('ix_catalog_items_name'), 'catalog_items', ['name'], unique=False)
    op.drop_index('ix_catalogs_name', table_name='catalogs')
    op.create_index(op.f('ix_catalogs_name'), 'catalogs', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_catalogs_name'), table_name='catalogs')
    op.create_index('ix_catalogs_name', 'catalogs', ['name'], unique=True)
    op.drop_index(op.f('ix_catalog_items_name'), table_name='catalog_items')
    op.create_index('ix_catalog_items_name', 'catalog_items', ['name'], unique=True)
    op.drop_index(op.f('ix_blockchain_contracts_name'), table_name='blockchain_contracts')
    op.create_index('ix_blockchain_contracts_name', 'blockchain_contracts', ['name'], unique=True)
    # ### end Alembic commands ###
