"""set index for seller_id in catalog

Revision ID: 55320a5f5f8d
Revises: 281fc4ff4ad4
Create Date: 2020-09-27 19:04:32.819388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55320a5f5f8d'
down_revision = '281fc4ff4ad4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_catalogs_seller_id'), 'catalogs', ['seller_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_catalogs_seller_id'), table_name='catalogs')
    # ### end Alembic commands ###
