"""empty message

Revision ID: c1f738e0734f
Revises: 129092d2868b
Create Date: 2020-11-04 18:41:33.027491

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c1f738e0734f'
down_revision = '129092d2868b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders',
                  sa.Column('amount', sa.Numeric(precision=10, scale=2),
                            nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'amount')
    # ### end Alembic commands ###
