[tool.poetry]
name = "chainvoice-client"
version = "0.1.0"
description = "A client library for accessing Chainvoice"

authors = []

readme = "README.md"
packages = [
    {include = "chainvoice_client"},
]
include = ["CHANGELOG.md", "chainvoice_client/py.typed"]


[tool.poetry.dependencies]
python = "^3.8"
httpx = "^0.13.3"

[tool.black]
line-length = 120
target_version = ['py38']
exclude = '''
(
  /(
    | \.git
    | \.venv
    | \.mypy_cache
  )/
)
'''

[tool.isort]
line_length = 120
multi_line_output = 3
include_trailing_comma = true

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"